#!/bin/sh
ping 8.8.8.8 -c 3
if [ $? == 0 ];then
	opkg update && opkg install bash motion kmod-usb-core kmod-usb2 \
	kmod-video-core kmod-video-uvc mailsend madplay ffmpeg
for i in 'usr/bin/fdi_cam usr/bin/ctimer.sh usr/bin/functioncctv';do
	chmod 0755 $i
	cp $i /usr/bin/
done
chmod 0755 www/cgi-bin/fdicctv
cp -r etc/config/fdicctv /etc/config/
cp -r www/cgi-bin/fdicctv /www/cgi-bin/
cp -r www/fdi.png /www/fdi.png
IP=`uci get network.lan.ipaddr`
uci set fdicctv.main.ipaddr="$IP:80"
uci set fdicctv.main.ipaddrcctv="$IP:8081"
uci commit fdicctv
mkdir -p /root/CCTV/TMP
mkdir -p /root/CCTV/ALARM
ln -s /root/CCTV/TMP /www/video
fdi_cam start
else
	echo "internet periksa lagi ya bro..."
fi
